markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]
url: https://nongdonghui.github.io/
author:
  name: 'nongdonghui'
  email: '357228560@qq.com'
encoding: utf-8